### ISSUE TITLE
AXCF2152 reading Analog value by API is not stable, different on PLCNext Engineer

### ISSUE THREAD

**Issue by hoangvanhai** [PLCnext/SampleRuntime#11]
Hello, I read the analog value from PLCnext runtime framework, follow the guide on [https://github.com/PLCnext/SampleRuntime/blob/master/getting-started/Part-03/README.md](url) the value is 16 bit integer type, but the value is not same the value in PLCNext Engineer watcher
I simulated on channel 0 and channel 1
![PLCNext_50](https://user-images.githubusercontent.com/3765264/74921911-05f71200-5401-11ea-90d6-8c18f57d7c21.jpg)
Here is the result on reading function, the name is Arp.Io.AxlC/0.IN1 & Arp.Io.AxlC/0.IN2
![Program_50](https://user-images.githubusercontent.com/3765264/74921919-0a232f80-5401-11ea-8b6a-713935a2ada5.jpg)

Please show me how to correct the setting before read AI value by c/c++ program ?

Sincerely,
HaiHoang

**Comment by martinboers** [comment]
Hello,

This problem is discussed in this thread on the PLCnext Community Forum:

https://www.plcnext-community.net/en/discussions-2-offcanvas/axioline-read-bitstring16-to-number.html

Please try swapping the bytes of the analog input values.

**Comment by mluhmann** [comment]
Issue solved in the PLCnext Community.

**Comment by hoangvanhai** [comment]
Thanks martinboers, sorry i late reply, my program need reboot the system use C program, the routine for reboot is:

```
sync();
setuid(0);
reboot(RB_AUTOBOOT);
```

but when use the code, system does not reboot, the fail led is flashing
![04d7757c0c3df763ae2c](https://user-images.githubusercontent.com/3765264/75509396-018eb280-5a1a-11ea-988c-ee99c825011f.jpg)

Could you send me an advise for this case ?

Sincerely,
HaiHoang

**Comment by martinboers** [comment]
Hello HaiHoang,

That is a more general question about C programming on the PLCnext Control platform - so the best place to get an answer to that question is in the [PLCnext Community Forum](https://www.plcnext-community.net/en/discussions-2-offcanvas/forums.html).

Please create a new post there - if I cannot answer it, then someone else surely will.

Thank you for your interest in this project!

Martin.

**Comment by hoangvanhai** [comment]
Thanks Martin, i will move the question to the community forum
HaiHoang.
