### ISSUE TITLE
Part 7, no administrator rights.

### ISSUE THREAD

**Issue by robinDetobel** [PLCnext/SampleRuntime#19]
As mentioned on the forum in part 7 there the comand "sudo setcap cap_net_bind_service,cap_net_admin,cap_net_raw,cap_sys_boot,cap_sys_nice,cap_sys_time+ep projects/runtime/runtime" but i am unable to execute this as is. Martin Boers told me i am supposed to change the settings for the administrator account. Maybe this should also be mentioned?

**Comment by martinboers** [comment]
This will be fixed in future.
One workaround is to grant the admin user full sudo privileges by editing the /etc/sudoers file (as root).
