### ISSUE TITLE
Could not read port count for adapter '1'

### ISSUE THREAD

**Issue by OWarneke** [PLCnext/SampleRuntime#2]
I am still having trouble getting everything to run smoothly. The application gets an exception on the code
`ArpSystemModule_Load("/usr/lib", "PLCNextApp", "./data/PLCNextApp.acf.settings");`

It seems the error message in 'Output.log' is 
" Could not read port count for adapter '1' " . What does this mean ?

See the output.log below:
[Output.log](https://github.com/PLCnext/SampleRuntime/files/3509637/Output.log)

This is my file-system:
```
admin@axcf2152:/opt/plcnext/PLCNext/PLCNextApp$ ls -la
total 392
drwxr-xr-x 6 admin plcnext   4096 Aug 16 14:19 .
drwxr-xr-x 3 admin plcnext   4096 Aug 14 14:56 ..
-rw-rw-r-- 1 admin plcnext   2764 Aug 16 12:18 Application.xml
drwxrwxr-x 3 admin plcnext   4096 Aug 16 11:19 Components
-rw-rw-r-- 1 admin plcnext   1580 Aug 16 14:24 Messages.log
drwxrwxr-x 2 admin plcnext  73728 Aug 16 12:18 Models
-rwxrwxr-x 1 admin plcnext 297536 Aug 16 11:20 PLCNextApp
drwxrwxr-x 3 admin plcnext   4096 Aug 16 13:20 data
drwxr-xr-x 2 admin plcnext   4096 Aug 16 14:18 lib

```
The 'data' folder only contains PLCNextApp.acf.config and PLCNextApp.acf.settings (I had to append .txt here for file attachment to work... ) :
[PLCNextApp.acf.settings.txt](https://github.com/PLCnext/SampleRuntime/files/3509654/PLCNextApp.acf.settings.txt)
[PLCNextApp.acf.config.txt](https://github.com/PLCnext/SampleRuntime/files/3509656/PLCNextApp.acf.config.txt)

_Originally posted by @RuneEspeseth in https://github.com/PLCnext/SampleRuntime/issues/1#issuecomment-522000703_

**Comment by OWarneke** [comment]
>  The application gets an exception on the code
ArpSystemModule_Load("/usr/lib", "PLCNextApp", "./data/PLCNextApp.acf.settings");

That is because the home directory of the user executing the plcnext application is not at `/opt/plcnext/PLCNext/PLCNextApp`.

Please try going with the full path to your data directory.
`/opt/plcnext/PLCNext/PLCNextApp/data/PLCNextApp.acf.settings`

As to why it is throwing a strange error code, I suspect you might have changed some default config files?

**Comment by RuneEspeseth** [comment]
I think something else is wrong. I changed the code to use full path for .settings, but I still got the same error. 

I have now done
```sudo recover-axcf2152 2```
to restore firmware.
Then i installed the 2019.6 firmware using 
```update-axcf2152```
Then I reinstalled my application as admin into /opt/plcnext/PLCNext/PLCNextApp
I then copied my .config file from /opt/plcnext/PLCNext/PLCNextApp/data to ~/projects/Default , and softlinked ~/projects/current to /opt/plcnext/PLCNext/PLCNextApp/

I then restarted plcnext using sudo '/etc/init.d/plcnext restart'

As far as I can see, I got the same error. See latest Output.log:
[Output.log](https://github.com/PLCnext/SampleRuntime/files/3510092/Output.log)

**Comment by OWarneke** [comment]
please try doing this procedure:

1. sudo recover-axcf2152 2

**Comment by RuneEspeseth** [comment]
The above procedure solved my issues. Thanks! :+1:
