### ISSUE TITLE
Description of automatic build task vscode

### ISSUE THREAD

**Issue by JanWillemPxC** [PLCnext/SampleRuntime#4]
At part one a little description of how to create this build task (ctrl + shift + b)

Lesson 1, step 6 describes how to create the build script
This is not an executable script right away
in the commandline execute chmod +xxx build-runtime.sh to make it executable

Once this script is exacutable you can run it

Step 7 describes the build task

once created the  tasks.json pres F1 to open the prompt
after pressing backspace to delete the ">" type the following:  tasks: configure default build task
Then you have to choose your newly created task in the drop down menu
it shows something like "Build runtime for AXCF2152 2019.6"

This couples the keyboard shortcut (CTRL + SHIFT + B) to the task described by tasks.json

And after that ctrl + shift + b will start this task

**Comment by martinboers** [comment]
Done. These instructions will appear in the next version.
Thanks for the input!
